commiting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,6 +58,7 @@ jobs:
         working-directory: terraform
 
       - name: Debug Print plan.json
+        if: github.event_name == 'push'
         run: |
           if [ -f plan.json ]; then
             echo "--- plan.json contents ---"
@@ -69,6 +70,7 @@ jobs:
         working-directory: terraform
 
       - name: Debug policy loading
+        if: github.event_name == 'push'
         run: |
           pwd
           echo "Terraform dir contents:"
@@ -77,20 +79,23 @@ jobs:
           ls -R ../policy || true
         working-directory: terraform
 
-      # - name: Enforce OPA Policies
-      #   run: |
-      #     if [ ! -f plan.json ]; then
-      #       echo "plan.json not found! Failing pipeline before policy check." >&2
-      #       exit 1
-      #     fi
-      #     conftest test plan.json --policy ../policy/
-      #   working-directory: terraform
+      - name: Enforce OPA Policies
+        if: github.event_name == 'push'
+        run: |
+          if [ ! -f plan.json ]; then
+            echo "plan.json not found! Failing pipeline before policy check." >&2
+            exit 1
+          fi
+          conftest test plan.json --policy ../policy/
+        working-directory: terraform
 
       - name: Install Infracost
+        if: github.event_name == 'pull_request'
         run: |
           curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
 
       - name: Run Infracost
+        if: github.event_name == 'pull_request'
         env:
           INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
         run: |
@@ -100,6 +105,7 @@ jobs:
             --out-file infracost.json
 
       - name: Convert cost to markdown
+        if: github.event_name == 'pull_request'
         run: |
           infracost output \
             --path infracost.json \
